language: php
php:
  - 5.6
  - 7.0
  - 7.1
env:
  - MAGENTO_VERSION=magento-mirror-1.9.4.0
  - MAGENTO_VERSION=magento-mirror-1.9.2.2
  - MAGENTO_VERSION=magento-mirror-1.9.1.0
script:
  - composer install --dev --no-interaction
  - phpunit
  - curl -sSL https://raw.githubusercontent.com/schmengler/MageTestStand/master/setup.sh | bash
before_deploy: .travis/bundle.sh
deploy:
  provider: releases
  api_key:
    secure: YBCy2em9MOCaxS5cG+MqUO0kcW7ELPXHSs6mpM/fG+CcKaSOlrEuXmxgaCC9OJsj3aybZJ7WeiuxphLpv7CcgN5/pv+RC1RyEU/5Mt13/fG4P4YNKCEmDPsSnPQVtLKQJIWby9jf0ZhznjJJ/SvwGYmfGF0mn3/yINg2eNF/f3Y=
  file:
    - "integernet-anonymizer.zip"
    - "integernet-anonymizer.tar.gz"
  skip_cleanup: true
  on:
    tags: true